/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const load_font_from_bytes: (a: any, b: number, c: number) => [number, number];
export const main: () => void;
export const wasm_bindgen__convert__closures_____invoke__h79516e5a765063e8: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h1f569fd52f354400: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1c7a64eba21993ac: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1c7a64eba21993ac_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0f9c9072d625c415: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0f9c9072d625c415_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0f9c9072d625c415_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1c7a64eba21993ac_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1c7a64eba21993ac_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0f9c9072d625c415_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0f9c9072d625c415_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1c7a64eba21993ac_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1c7a64eba21993ac_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1c7a64eba21993ac_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0f9c9072d625c415_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1c7a64eba21993ac_15: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h5b865169ef894462: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
