/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const load_font_from_bytes: (a: any, b: number, c: number) => [number, number];
export const main: () => void;
export const wasm_bindgen__convert__closures_____invoke__hded5de4c19d0c817: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h0e556c15842f21f6: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h050ad23bd5621df1: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h050ad23bd5621df1_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h335f69c444b438aa: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h335f69c444b438aa_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h335f69c444b438aa_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h050ad23bd5621df1_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h050ad23bd5621df1_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h335f69c444b438aa_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h335f69c444b438aa_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h050ad23bd5621df1_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h050ad23bd5621df1_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h050ad23bd5621df1_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h335f69c444b438aa_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h050ad23bd5621df1_15: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h5b553ca1cb5f3233: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
