/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_compilationresult_free: (a: number, b: number) => void;
export const __wbg_wrappedcompiledcomp_free: (a: number, b: number) => void;
export const __wbg_wrappedinstance_free: (a: number, b: number) => void;
export const compilationresult_component: (a: number) => number;
export const compilationresult_diagnostics: (a: number) => any;
export const compilationresult_error_string: (a: number) => [number, number];
export const compile_from_string: (a: number, b: number, c: number, d: number, e: number) => any;
export const compile_from_string_with_style: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const init: () => void;
export const run_event_loop: () => [number, number];
export const wrappedcompiledcomp_create: (a: number, b: number, c: number) => [number, number, number];
export const wrappedcompiledcomp_create_with_existing_window: (a: number, b: number) => [number, number, number];
export const wrappedcompiledcomp_run: (a: number, b: number, c: number) => void;
export const wrappedinstance_hide: (a: number) => [number, number, number];
export const wrappedinstance_show: (a: number) => [number, number, number];
export const wasm_bindgen__convert__closures_____invoke__h2a188e4fd3013438: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h638e679038bf502d: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h638e679038bf502d_29: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h638e679038bf502d_30: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h28a12b0497363e7b: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h28a12b0497363e7b_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2a2b01563100e89a: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2a2b01563100e89a_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2a2b01563100e89a_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h28a12b0497363e7b_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h28a12b0497363e7b_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2a2b01563100e89a_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2a2b01563100e89a_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h28a12b0497363e7b_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h28a12b0497363e7b_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h28a12b0497363e7b_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2a2b01563100e89a_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h28a12b0497363e7b_15: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h437a3093eaf51212: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
