/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: () => void;
export const slint_qt_get_widget: (a: number) => number;
export const send_keyboard_string_sequence: (a: number, b: number) => void;
export const slint_get_mocked_time: () => bigint;
export const slint_mock_elapsed_time: (a: bigint) => void;
export const slint_send_keyboard_char: (a: number, b: number, c: number) => void;
export const slint_send_keyboard_key_text: (a: number, b: number, c: number) => void;
export const slint_send_mouse_click: (a: number, b: number, c: number) => void;
export const wasm_bindgen__closure__destroy__h15e8dc61c3af17ae: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h4706bb7c0208f7e1: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h10936871c2950272: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h21a15242856ef664: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h21a15242856ef664_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0a516a4f910e2c7e: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0a516a4f910e2c7e_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0a516a4f910e2c7e_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h21a15242856ef664_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h21a15242856ef664_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0a516a4f910e2c7e_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0a516a4f910e2c7e_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h21a15242856ef664_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h21a15242856ef664_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h21a15242856ef664_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0a516a4f910e2c7e_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h21a15242856ef664_15: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hbab0a05a297ae0bc: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
