/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: () => void;
export const slint_qt_get_widget: (a: number) => number;
export const send_keyboard_string_sequence: (a: number, b: number) => void;
export const slint_get_mocked_time: () => bigint;
export const slint_mock_elapsed_time: (a: bigint) => void;
export const slint_send_keyboard_char: (a: number, b: number, c: number) => void;
export const slint_send_keyboard_key_text: (a: number, b: number, c: number) => void;
export const slint_send_mouse_click: (a: number, b: number, c: number) => void;
export const wasm_bindgen__closure__destroy__h17d0cafd1e942192: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h1304f3497aa49085: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h028d5def98a7af2c: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3dbb5ae9fc7672b4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3dbb5ae9fc7672b4_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h06e4d4a609fee0ac: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h06e4d4a609fee0ac_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h06e4d4a609fee0ac_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3dbb5ae9fc7672b4_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3dbb5ae9fc7672b4_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h06e4d4a609fee0ac_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h06e4d4a609fee0ac_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3dbb5ae9fc7672b4_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3dbb5ae9fc7672b4_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3dbb5ae9fc7672b4_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h06e4d4a609fee0ac_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3dbb5ae9fc7672b4_15: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h18f1a674c24b75b1: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
