/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: () => void;
export const slint_qt_get_widget: (a: number) => number;
export const send_keyboard_string_sequence: (a: number, b: number) => void;
export const slint_get_mocked_time: () => bigint;
export const slint_mock_elapsed_time: (a: bigint) => void;
export const slint_send_keyboard_char: (a: number, b: number, c: number) => void;
export const slint_send_keyboard_key_text: (a: number, b: number, c: number) => void;
export const slint_send_mouse_click: (a: number, b: number, c: number) => void;
export const wasm_bindgen__closure__destroy__h35cc955239a8062c: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h228e059c70d549e7: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__ha7c71252b42409d3: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h56a4ef1ff0967eff: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hdd882de6c516954f: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h1db32f500f188270: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1db32f500f188270_1: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1db32f500f188270_2: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1db32f500f188270_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1db32f500f188270_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1db32f500f188270_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0fab915dfdd53e5c: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0fab915dfdd53e5c_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0fab915dfdd53e5c_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0fab915dfdd53e5c_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0fab915dfdd53e5c_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0fab915dfdd53e5c_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0fab915dfdd53e5c_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0fab915dfdd53e5c_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h5b0f36d0aef2bef8: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
