/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: () => void;
export const send_keyboard_string_sequence: (a: number, b: number) => void;
export const slint_get_mocked_time: () => bigint;
export const slint_mock_elapsed_time: (a: bigint) => void;
export const slint_send_keyboard_char: (a: number, b: number, c: number) => void;
export const slint_send_keyboard_key_text: (a: number, b: number, c: number) => void;
export const slint_send_mouse_click: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hc4aecf8cde323b79: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h8f821e30a35b744f: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h03e30335f364b188: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h03e30335f364b188_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2a56368c8eebc30c: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2a56368c8eebc30c_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2a56368c8eebc30c_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h03e30335f364b188_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h03e30335f364b188_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2a56368c8eebc30c_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2a56368c8eebc30c_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h03e30335f364b188_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h03e30335f364b188_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h03e30335f364b188_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2a56368c8eebc30c_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h03e30335f364b188_15: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h14b51c9d66449ca6: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
