/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: () => void;
export const slint_qt_get_widget: (a: number) => number;
export const send_keyboard_string_sequence: (a: number, b: number) => void;
export const slint_get_mocked_time: () => bigint;
export const slint_mock_elapsed_time: (a: bigint) => void;
export const slint_send_keyboard_char: (a: number, b: number, c: number) => void;
export const slint_send_keyboard_key_text: (a: number, b: number, c: number) => void;
export const slint_send_mouse_click: (a: number, b: number, c: number) => void;
export const wasm_bindgen__closure__destroy__h1da855778a6923b2: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h028553e66040b7df: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h4234e91de2fa7cf5: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hd4f991ab31b7ec37: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1a920804e7eb1d8a: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h514c244e9d4b663a: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h514c244e9d4b663a_1: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h514c244e9d4b663a_2: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h514c244e9d4b663a_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h514c244e9d4b663a_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h514c244e9d4b663a_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h032b22b73a529611: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h032b22b73a529611_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h032b22b73a529611_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h032b22b73a529611_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h032b22b73a529611_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h032b22b73a529611_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h032b22b73a529611_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h032b22b73a529611_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hcc23bc2d259a6d64: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
