/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function slint_native_style_metrics_init(a: number): void;
export function slint_native_style_metrics_deinit(a: number): void;
export function slint_mock_elapsed_time(a: number): void;
export function slint_send_mouse_click(a: number, b: number, c: number, d: number): void;
export function send_keyboard_string_sequence(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function __wbg_compilationresult_free(a: number): void;
export function compilationresult_component(a: number): number;
export function compilationresult_diagnostics(a: number): number;
export function compilationresult_error_string(a: number, b: number): void;
export function compile_from_string(a: number, b: number, c: number, d: number, e: number): number;
export function compile_from_string_with_style(a: number, b: number, c: number, d: number, e: number, f: number, g: number): number;
export function __wbg_wrappedcompiledcomp_free(a: number): void;
export function wrappedcompiledcomp_run(a: number, b: number, c: number): void;
export function wrappedcompiledcomp_create(a: number, b: number, c: number, d: number): void;
export function __wbg_wrappedinstance_free(a: number): void;
export function wrappedinstance_show(a: number): void;
export function wrappedinstance_hide(a: number): void;
export function run_event_loop(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__ha7ba65a9ff3bd2b3(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h16562c8b6298d6d8(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__ha946ca5b9959c961(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h5b38d84027834f04(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h307d8dc22a4d8d23(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h29d12b076afb078d(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hccfe5c841e23121e(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h8969841752679422(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hba9cdf5b94cbc50c(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h04e299a70d43ff75(a: number, b: number): void;
export function _dyn_core__ops__function__Fn__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h03075c211b24fec1(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__Fn__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h0cc6d00806ab17d4(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__Fn__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hd0475c8f94ac9b87(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__Fn__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h2cff764f6a9be232(a: number, b: number, c: number): void;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h341283964cefd133(a: number, b: number, c: number, d: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
