/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function sixtyfps_flickable_data_init(a: number): void;
export function sixtyfps_flickable_data_free(a: number): void;
export function sixtyfps_mock_elapsed_time(a: number): void;
export function sixtyfps_send_mouse_click(a: number, b: number, c: number, d: number): void;
export function send_keyboard_string_sequence(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function sixtyfps_qt_get_widget(a: number): number;
export function __wbg_compilationresult_free(a: number): void;
export function compilationresult_component(a: number): number;
export function compilationresult_diagnostics(a: number): number;
export function compilationresult_error_string(a: number, b: number): void;
export function compile_from_string(a: number, b: number, c: number, d: number, e: number): number;
export function compile_from_string_with_style(a: number, b: number, c: number, d: number, e: number, f: number, g: number): number;
export function __wbg_wrappedcompiledcomp_free(a: number): void;
export function wrappedcompiledcomp_run(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hcbef8dcce81d1a22(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hcebbc3fabd48a71a(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hb59f8048b31db7a7(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hd53e5ba311ad1381(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h377fb4d1fc64d544(a: number, b: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__ha2b3f1f40a0d2ca3(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hc08cbf9d3336f1c2(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h1710ae5b784ab934(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h4dd48a318760b9e2(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h4718588e1ee2cef7(a: number, b: number, c: number): void;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__hf291c1f0776fe258(a: number, b: number, c: number, d: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
