/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function slint_mock_elapsed_time(a: number): void;
export function slint_send_mouse_click(a: number, b: number, c: number, d: number): void;
export function slint_send_keyboard_char(a: number, b: number, c: number): void;
export function send_keyboard_string_sequence(a: number, b: number): void;
export function __wbg_compilationresult_free(a: number): void;
export function compilationresult_component(a: number): number;
export function compilationresult_diagnostics(a: number): number;
export function compilationresult_error_string(a: number, b: number): void;
export function compile_from_string(a: number, b: number, c: number, d: number, e: number): number;
export function compile_from_string_with_style(a: number, b: number, c: number, d: number, e: number, f: number, g: number): number;
export function __wbg_wrappedcompiledcomp_free(a: number): void;
export function wrappedcompiledcomp_run(a: number, b: number, c: number): void;
export function wrappedcompiledcomp_create(a: number, b: number, c: number, d: number): void;
export function wrappedcompiledcomp_create_with_existing_window(a: number, b: number, c: number): void;
export function __wbg_wrappedinstance_free(a: number): void;
export function wrappedinstance_show(a: number, b: number): void;
export function wrappedinstance_hide(a: number, b: number): void;
export function wrappedinstance_highlight(a: number, b: number, c: number, d: number): void;
export function wrappedinstance_set_design_mode(a: number, b: number): void;
export function wrappedinstance_on_element_selected(a: number, b: number): void;
export function run_event_loop(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__Fn__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h784fb9abdf9da38e(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h0ca747870be9d00d(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hac9d631b8c71ff56(a: number, b: number): void;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__hc8b20f3c886e4a77(a: number, b: number, c: number, d: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
