/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const load_font_from_bytes: (a: any, b: number, c: number) => [number, number];
export const main: () => void;
export const wasm_bindgen__convert__closures_____invoke__hc054fe4cf5c0978c: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h641ea2c902714126: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0badc81a01258a31: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0badc81a01258a31_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h35df91da0f366d5c: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h35df91da0f366d5c_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h35df91da0f366d5c_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0badc81a01258a31_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0badc81a01258a31_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h35df91da0f366d5c_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h35df91da0f366d5c_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0badc81a01258a31_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0badc81a01258a31_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0badc81a01258a31_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h35df91da0f366d5c_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0badc81a01258a31_15: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0bce5889441a2bb7: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
