/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function sixtyfps_flickable_data_init(a: number): void;
export function sixtyfps_flickable_data_free(a: number): void;
export function sixtyfps_mock_elapsed_time(a: number): void;
export function sixtyfps_send_mouse_click(a: number, b: number, c: number, d: number): void;
export function send_keyboard_string_sequence(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function __wbg_compilationresult_free(a: number): void;
export function compilationresult_component(a: number): number;
export function compilationresult_diagnostics(a: number): number;
export function compilationresult_error_string(a: number, b: number): void;
export function compile_from_string(a: number, b: number, c: number, d: number, e: number): number;
export function __wbg_wrappedcompiledcomp_free(a: number): void;
export function wrappedcompiledcomp_run(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hf2080576ae65677a(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h86019e73bc237761(a: number, b: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h0a17a18a51716935(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__ha80981123cedcf5b(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h2a57749bc5c70043(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hf4cd0125d9f28876(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h5474dbf3284ab3a5(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__haecb6e290b8fe25c(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h2e0513e6fd783dab(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h7ebc442dd30bd428(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h0b968c364235550e(a: number, b: number, c: number, d: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
