/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const slint_qt_get_widget: (a: number) => number;
export const send_keyboard_string_sequence: (a: number, b: number) => void;
export const slint_get_mocked_time: () => bigint;
export const slint_mock_elapsed_time: (a: bigint) => void;
export const slint_send_keyboard_char: (a: number, b: number, c: number) => void;
export const slint_send_keyboard_key_text: (a: number, b: number, c: number) => void;
export const slint_send_mouse_click: (a: number, b: number, c: number) => void;
export const main: () => void;
export const wasm_bindgen__closure__destroy__h021d7984897f6c9e: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h4706bb7c0208f7e1: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h10936871c2950272: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h01f305c84eb3f245: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h01f305c84eb3f245_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1030e503aa9bcaba: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1030e503aa9bcaba_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1030e503aa9bcaba_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h01f305c84eb3f245_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h01f305c84eb3f245_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1030e503aa9bcaba_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1030e503aa9bcaba_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h01f305c84eb3f245_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h01f305c84eb3f245_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h01f305c84eb3f245_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1030e503aa9bcaba_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h01f305c84eb3f245_15: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h5cac0a041446c6cd: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
