/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const slint_qt_get_widget: (a: number) => number;
export const send_keyboard_string_sequence: (a: number, b: number) => void;
export const slint_get_mocked_time: () => bigint;
export const slint_mock_elapsed_time: (a: bigint) => void;
export const slint_send_keyboard_char: (a: number, b: number, c: number) => void;
export const slint_send_mouse_click: (a: number, b: number, c: number) => void;
export const main: () => void;
export const wasm_bindgen__closure__destroy__h04842603350e4976: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h1304f3497aa49085: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h028d5def98a7af2c: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h06cfba3b644fa6cb: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h06cfba3b644fa6cb_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h31448167b13ee3eb: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h31448167b13ee3eb_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h31448167b13ee3eb_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h06cfba3b644fa6cb_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h06cfba3b644fa6cb_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h31448167b13ee3eb_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h31448167b13ee3eb_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h06cfba3b644fa6cb_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h06cfba3b644fa6cb_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h06cfba3b644fa6cb_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h31448167b13ee3eb_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h06cfba3b644fa6cb_15: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hfe96d30ee70f2e84: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
