/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function slint_mock_elapsed_time(a: number): void;
export function slint_send_mouse_click(a: number, b: number, c: number, d: number): void;
export function slint_send_keyboard_char(a: number, b: number, c: number): void;
export function send_keyboard_string_sequence(a: number, b: number): void;
export function __wbg_compilationresult_free(a: number): void;
export function compilationresult_component(a: number): number;
export function compilationresult_diagnostics(a: number): number;
export function compilationresult_error_string(a: number, b: number): void;
export function compile_from_string(a: number, b: number, c: number, d: number, e: number): number;
export function compile_from_string_with_style(a: number, b: number, c: number, d: number, e: number, f: number, g: number): number;
export function __wbg_wrappedcompiledcomp_free(a: number): void;
export function wrappedcompiledcomp_run(a: number, b: number, c: number): void;
export function wrappedcompiledcomp_create(a: number, b: number, c: number, d: number): void;
export function wrappedcompiledcomp_create_with_existing_window(a: number, b: number, c: number): void;
export function __wbg_wrappedinstance_free(a: number): void;
export function wrappedinstance_show(a: number, b: number): void;
export function wrappedinstance_hide(a: number, b: number): void;
export function run_event_loop(a: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function wasm_bindgen__convert__closures__invoke1__h33c21d16f8b95dad(a: number, b: number, c: number): void;
export function wasm_bindgen__convert__closures__invoke1_mut__h0d99507bd9fd7c26(a: number, b: number, c: number): void;
export function wasm_bindgen__convert__closures__invoke0_mut__h15f2c45f0a976089(a: number, b: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h9131d7a49f7a1c00(a: number, b: number, c: number, d: number): void;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
