/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: () => void;
export const slint_qt_get_widget: (a: number) => number;
export const send_keyboard_string_sequence: (a: number, b: number) => void;
export const slint_get_mocked_time: () => bigint;
export const slint_mock_elapsed_time: (a: bigint) => void;
export const slint_send_keyboard_char: (a: number, b: number, c: number) => void;
export const slint_send_keyboard_key_text: (a: number, b: number, c: number) => void;
export const slint_send_mouse_click: (a: number, b: number, c: number) => void;
export const wasm_bindgen__closure__destroy__h4b98ecf228858d73: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h0481d65c1238ab81: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h18d76213fc3bf392: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h38ebc81fda68204e: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2dbc277ad7e5f012: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h54057ba94edcc5cf: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h54057ba94edcc5cf_1: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h54057ba94edcc5cf_2: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h54057ba94edcc5cf_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h54057ba94edcc5cf_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h54057ba94edcc5cf_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1766b09e12be44da: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1766b09e12be44da_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1766b09e12be44da_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1766b09e12be44da_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1766b09e12be44da_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1766b09e12be44da_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1766b09e12be44da_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1766b09e12be44da_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hb1a134338e73e567: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
