/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const load_font_from_bytes: (a: any, b: number, c: number) => [number, number];
export const main: () => void;
export const wasm_bindgen__convert__closures_____invoke__haeeddabfe4ed33e0: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h23469c4196ca82c9: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0174408576a3a130: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0174408576a3a130_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h374b2ea9bceee972: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h374b2ea9bceee972_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h374b2ea9bceee972_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0174408576a3a130_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0174408576a3a130_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h374b2ea9bceee972_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h374b2ea9bceee972_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0174408576a3a130_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0174408576a3a130_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0174408576a3a130_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h374b2ea9bceee972_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0174408576a3a130_15: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hb49bca0bf7b11b8b: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
