/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const load_font_from_bytes: (a: any, b: number, c: number) => [number, number];
export const main: () => void;
export const wasm_bindgen__convert__closures_____invoke__h2cbe8d7de531c3fc: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h152df601c26f68a7: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h16780fe5cda60e7f: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h16780fe5cda60e7f_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0d5f2f04dab0881c: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0d5f2f04dab0881c_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0d5f2f04dab0881c_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h16780fe5cda60e7f_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h16780fe5cda60e7f_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0d5f2f04dab0881c_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0d5f2f04dab0881c_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h16780fe5cda60e7f_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h16780fe5cda60e7f_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h16780fe5cda60e7f_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0d5f2f04dab0881c_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h16780fe5cda60e7f_15: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__ha7edbb9a3415bb0f: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
