/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const load_font_from_bytes: (a: any, b: number, c: number) => [number, number];
export const main: () => void;
export const send_keyboard_string_sequence: (a: number, b: number) => void;
export const slint_get_mocked_time: () => bigint;
export const slint_mock_elapsed_time: (a: bigint) => void;
export const slint_send_keyboard_char: (a: number, b: number, c: number) => void;
export const slint_send_keyboard_key_text: (a: number, b: number, c: number) => void;
export const slint_send_mouse_click: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h4b68a650e08ff1d4: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h0087bbe320fe3f34: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10343dfba8d9814b: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10343dfba8d9814b_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h4bbecbe70402bf8a: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h4bbecbe70402bf8a_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h4bbecbe70402bf8a_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10343dfba8d9814b_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10343dfba8d9814b_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h4bbecbe70402bf8a_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h4bbecbe70402bf8a_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10343dfba8d9814b_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10343dfba8d9814b_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10343dfba8d9814b_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h4bbecbe70402bf8a_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10343dfba8d9814b_15: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hc4b29f520cdc6595: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
