/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: () => void;
export const slint_qt_get_widget: (a: number) => number;
export const send_keyboard_string_sequence: (a: number, b: number) => void;
export const slint_get_mocked_time: () => bigint;
export const slint_mock_elapsed_time: (a: bigint) => void;
export const slint_send_keyboard_char: (a: number, b: number, c: number) => void;
export const slint_send_mouse_click: (a: number, b: number, c: number) => void;
export const wasm_bindgen__closure__destroy__h10eda77799abebda: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h177cec7ec5b179d3: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h4531b845baa3da33: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__he3422ed39c2002fb: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3229bed223ba036c: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h29bb0363882beda4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h29bb0363882beda4_1: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h29bb0363882beda4_2: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h29bb0363882beda4_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h29bb0363882beda4_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h29bb0363882beda4_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h262d80eadcbc4244: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h262d80eadcbc4244_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h262d80eadcbc4244_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h262d80eadcbc4244_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h262d80eadcbc4244_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h262d80eadcbc4244_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h262d80eadcbc4244_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h262d80eadcbc4244_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h77138cec5f98c1dd: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
