/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_compilationresult_free: (a: number, b: number) => void;
export const __wbg_wrappedcompiledcomp_free: (a: number, b: number) => void;
export const __wbg_wrappedinstance_free: (a: number, b: number) => void;
export const compilationresult_component: (a: number) => number;
export const compilationresult_diagnostics: (a: number) => any;
export const compilationresult_error_string: (a: number) => [number, number];
export const compile_from_string: (a: number, b: number, c: number, d: number, e: number) => any;
export const compile_from_string_with_style: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const init: () => void;
export const run_event_loop: () => [number, number];
export const wrappedcompiledcomp_create: (a: number, b: number, c: number) => [number, number, number];
export const wrappedcompiledcomp_create_with_existing_window: (a: number, b: number) => [number, number, number];
export const wrappedcompiledcomp_run: (a: number, b: number, c: number) => void;
export const wrappedinstance_hide: (a: number) => [number, number, number];
export const wrappedinstance_show: (a: number) => [number, number, number];
export const wasm_bindgen__convert__closures_____invoke__h4fc33ad255d8be9c: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h265dbaa1cc74171d: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h265dbaa1cc74171d_29: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h265dbaa1cc74171d_30: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0fe29754c7d9df25: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0fe29754c7d9df25_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1624f8350666368a: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1624f8350666368a_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1624f8350666368a_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0fe29754c7d9df25_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0fe29754c7d9df25_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1624f8350666368a_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1624f8350666368a_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0fe29754c7d9df25_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0fe29754c7d9df25_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0fe29754c7d9df25_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1624f8350666368a_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0fe29754c7d9df25_15: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h73a76ea106dec545: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
