/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const load_font_from_bytes: (a: any, b: number, c: number) => [number, number];
export const main: () => void;
export const slint_qt_get_widget: (a: number) => number;
export const send_keyboard_string_sequence: (a: number, b: number) => void;
export const slint_get_mocked_time: () => bigint;
export const slint_mock_elapsed_time: (a: bigint) => void;
export const slint_send_keyboard_char: (a: number, b: number, c: number) => void;
export const slint_send_keyboard_key_text: (a: number, b: number, c: number) => void;
export const slint_send_mouse_click: (a: number, b: number, c: number) => void;
export const wasm_bindgen__closure__destroy__h118ad55dcbc5a076: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h5065f82ccd58e8f7: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h10745fcab48382fd: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3659b8c98a55d730: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3659b8c98a55d730_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h35a5a3436af381dc: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h35a5a3436af381dc_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h35a5a3436af381dc_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3659b8c98a55d730_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3659b8c98a55d730_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h35a5a3436af381dc_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h35a5a3436af381dc_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3659b8c98a55d730_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3659b8c98a55d730_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3659b8c98a55d730_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h35a5a3436af381dc_14: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3659b8c98a55d730_15: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__he4581bf1bbfe009c: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
